<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Trabajo 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Trabajo4_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo4_files/libs/quarto-html/quarto.js"></script>
<script src="Trabajo4_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo4_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="trabajo-1" class="level2">
<h2 class="anchored" data-anchor-id="trabajo-1"><strong>Trabajo 1</strong></h2>
</section>
<section id="la-pobreza-extrema-y-el-desarrollo-humano" class="level1">
<h1><strong>La pobreza extrema y el desarrollo humano</strong></h1>
<p>Por Berta Bugueño</p>
<p>Durante los últimos años se ha visto una disminución de la pobreza en Chile, especialmente en las zonas rurales del país, la multidimencionalidad que influye en este acontecer sociológico es, desde el punto de vista de la ética social cristiana donde “<em>se subraya la relevancia de realizar evaluaciones cualitativas sistemáticas sobre la pobreza y el desarrollo humano […] La pobreza y el desarrollo humano son fenómenos sociales complejos</em>” <span class="citation" data-cites="daherEvaluacionCualitativaSistematica2019">[@daherEvaluacionCualitativaSistematica2019]</span></p>
<p>Vamos a estudiar que nuevos trabajos y oportunidades de acceso a tecnologías, conectividades, educación, espacios públicos y vivienda han incidido para que la brecha de la pobreza en las zonas rurales haya variado y disminuido considerablemente desde 1990, según un estudio de Pérez, “<em>la distancia al mercado incide directamente sobre la pobreza de las personas, la movilidad influye directamente</em>”. <span class="citation" data-cites="perezEfectoDistanciaMercado2013">[@perezEfectoDistanciaMercado2013]</span>.</p>
<p>La mayoría de las zonas rurales en Chile tiene muy mala conectividad, en las comunas rurales no existe el Metro, los otros medios de transportes son con frecuencias, en su mayoría muy distantes, sus máquinas antiguas, así mismo la educación es un factor preponderante para salir de la pobreza, en muchos casos en los sectores donde hay pobreza extrema, existe sólo educación municipalizada y no existe ninguna entidad de educación superior.</p>
<p>Por otra parte el acceso a la vivienda también es un tema relevante y es uno de los factores que mide la pobreza, en algunos sectores la denominación de suelo impide que se realicen proyectos habitacionales.</p>
<p>también es atendible el cómo perciben las personas la desigualdad, que según Paradox” <em>Las investigaciones sugieren que los ciudadanos de las sociedades desiguales están menos preocupados que las sociedades más igualitarias</em>”<span class="citation" data-cites="mijsParadoxInequalityIncome2021a">[@mijsParadoxInequalityIncome2021a]</span></p>
<p>Un Factor muy importante es la salud mental, Vera-Bachmann establece que “<em>estudios constatan que la situación social de pobreza socioeconómica es un factor de riesgo psicosocial en general y de salud mental en particular, que afecta de manera especial a los sectores rurales</em>” tambien explica la relación de hogares de extrema pobreza con la cantidad de niños, existiendo una relación entre estas variables, así mismo en su artículo establece que niños y jóvenes abandonan los estudios e ingresan prematuramente al mundo del trabajo <span class="citation" data-cites="bachmannResiliencePovertyRurality2015">[@bachmannResiliencePovertyRurality2015]</span></p>
<p>Se espera dilucidar que, a medida que aumentan las oportunidades de acceso a bienes y servicios, especialmente la educación, que mejoran la calidad de vida en las zonas rurales, disminuya la pobreza de sus habitantes. Desde el punto de vista teológico se puede observar que: “<em>considerando las múltiples dimensiones involucradas, así como el horizonte humanizador y del bien común. Se destaca la necesidad de realizar evaluaciones cualitativas sistemáticas a nivel nacional e internacional que complementen las mediciones cuantitativas, presentando sus aportes y consideraciones metodológicas y éticas. Finalmente, abordar las implicaciones y conexiones entre estas nociones, así como los desafíos conceptuales y metodológicos para la evaluación de la pobreza y el desarrollo humano en el marco de la Ética Social Cristiana</em>” <span class="citation" data-cites="daherEvaluacionCualitativaSistematica201">[@daherEvaluacionCualitativaSistematica201]</span></p>
<pre class="unnumbered unnumbered unnumbered"><code>title: "Trabajo 2"
format: html
editor: visual
bibliography: Estratificacion social (brechas de pobreza).bib
link-citations: true</code></pre>
</section>
<section id="trabajo-2" class="level1">
<h1>Trabajo 2</h1>
</section>
<section id="la-pobreza-extrema-y-el-desarrollo-humano-1" class="level1">
<h1>La pobreza extrema y el desarrollo humano</h1>
<section id="cargar-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="cargar-base-de-datos">Cargar base de datos</h2>
<p>En este trabajo se toma la desición de cambiar la base de datos a EBS 2021 (Encuesta de Bienestar Social), porque la base de datos del trabajo N° 1 fue muy difícil de cargar, y no contaba con todos los datos necesarios para el planteamiento del trabajo o investigación a realizar.</p>
</section>
<section id="selección-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="selección-de-variables">Selección de variables</h2>
<p>Se trabajará con variables nivel educacional, satisfacción de ingresos, satisfacción de vivienda educación ingresos, zona, de la encuesta EBS (Encuesta de bienestar Social), que se ejecuta en conjunto por el Ministerio de Desarrollo Social y el Instituto Nacional de Estadísticas (INE) en Chile, contiene estas variables que se corresponden a lo que esta investigación se plantea dilucidar.</p>
<p>En el caso de la variable nivel educacional (e6a) se toma la desición de realizar la investigación tomando esta variable de la base de datos del 2020 porque la del 2021 tiene muchos casos perdidos, además la misma base de datos EBS 2021 incluye la variable de la Casen del nivel educacional del año 2020</p>
</section>
</section>
<section id="tabla-descriptiva-general" class="level1">
<h1>Tabla descriptiva general</h1>
<div class="cell">

</div>
</section>
<section id="operacionalización-de-variables" class="level1">
<h1>Operacionalización de variables</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>satisfacción con el nivel educacional (x) &lt;numeric&gt; 
# total N=10921 valid N=10921 mean=3.38 sd=1.18

Value |                      Label |    N | Raw % | Valid % | Cum. %
--------------------------------------------------------------------
    1 | 1. Totalmente insatisfecho |  536 |  4.91 |    4.91 |   4.91
    2 |            2. Insatisfecho | 2940 | 26.92 |   26.92 |  31.83
    3 |             3. Indiferente | 1028 |  9.41 |    9.41 |  41.24
    4 |              4. Satisfecho | 4655 | 42.62 |   42.62 |  83.87
    5 |   5. Totalmente satisfecho | 1762 | 16.13 |   16.13 | 100.00
 &lt;NA&gt; |                       &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>satisfacción con los ingresos (x) &lt;numeric&gt; 
# total N=10921 valid N=10921 mean=2.93 sd=1.18

Value |                      Label |    N | Raw % | Valid % | Cum. %
--------------------------------------------------------------------
    1 | 1. Totalmente insatisfecho | 1165 | 10.67 |   10.67 |  10.67
    2 |            2. Insatisfecho | 3759 | 34.42 |   34.42 |  45.09
    3 |             3. Indiferente | 1403 | 12.85 |   12.85 |  57.93
    4 |              4. Satisfecho | 3818 | 34.96 |   34.96 |  92.89
    5 |   5. Totalmente satisfecho |  776 |  7.11 |    7.11 | 100.00
 &lt;NA&gt; |                       &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>satisfacción con la vivienda (x) &lt;numeric&gt; 
# total N=10921 valid N=10921 mean=3.72 sd=1.07

Value |                      Label |    N | Raw % | Valid % | Cum. %
--------------------------------------------------------------------
    1 | 1. Totalmente insatisfecho |  362 |  3.31 |    3.31 |   3.31
    2 |            2. Insatisfecho | 1763 | 16.14 |   16.14 |  19.46
    3 |             3. Indiferente |  797 |  7.30 |    7.30 |  26.76
    4 |              4. Satisfecho | 5652 | 51.75 |   51.75 |  78.51
    5 |   5. Totalmente satisfecho | 2347 | 21.49 |   21.49 | 100.00
 &lt;NA&gt; |                       &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>efecto de la educación sobre los ingresos (x) &lt;numeric&gt; 
# total N=10921 valid N=10188 mean=2.81 sd=1.30

Value |       Label |    N | Raw % | Valid % | Cum. %
-----------------------------------------------------
    1 |     1. Nada | 2338 | 21.41 |   22.95 |  22.95
    2 |     2. Poco | 1796 | 16.45 |   17.63 |  40.58
    3 |     3. Algo | 2480 | 22.71 |   24.34 |  64.92
    4 | 4. Bastante | 2637 | 24.15 |   25.88 |  90.80
    5 |    5. Mucho |  937 |  8.58 |    9.20 | 100.00
 &lt;NA&gt; |        &lt;NA&gt; |  733 |  6.71 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>En primer lugar en satisfacción con el nivel educacional, de un total de 10188 encuestados, el mayor porcentaje corresponde a satisfechos con 42,82% (hay que poner 4.362 encuestados) y con la menor preferencia que es 4.68% (o hay que poner 477 encuestados) para totalmente insatisfecho, la desviación estándar es de 1.17 y la media de 3.39. Siendo la suma de satisfecho con totalmente satisfecho de 6.003 encuestados se puede decir que de la muestra de la población de encuestados un 58.93% se manifiesta encontrarse satisfecho o totalmente satisfecho con el nivel educacional.</p>
<p>Satisfacción con los ingresos, de una muestra de 10.188 encuestados, 3.573 manifestaron estar satisfecho, pero en una cifra muy cercana, 3.521 personas manifestaron estar insatisfecho, la cifra más baja es con los encuestados que dijeron estar totalmente satisfecho que corresponden a 721 encuestados, la desviación estándar es de 1.18 y la media de 2.93. Lo que indica este resultado es que de los encuestados pocas personas se encuentran totalmente satisfechas y satisfechos e insatisfechos son muy similares respecto a la satisfacción de ingresos de la muestra.</p>
<p>Satisfacción con la vivienda, del total de la muestra de 10.188 encuestados, donde la media es 3.71 y la desviación estándar 1.08, la mayor preferencia es para “satisfecho” con 5.258 encuestados con un 51.61% y la menor preferencia 347 encuestados “Totalmente insatisfecho” que representan un 3.41%. Por lo que se puede decir que la mayoría de los encuestados se encuentra satisfecho con la vivienda.</p>
<p>Efecto de educación sobre los ingresos, con una muestra poblacional de 10.188 encuestados, donde la media es 2.81 y la desviación estándar en 1.30 2.637 de los encuestados opinan que el efecto de la educación sobre los ingresos es “bastante”, y la cifra más baja quienes piensan que el efecto es “mucho” con 937 encuestados, sin embargo si sumamos quienes opinaron que loa efectos son nada o poco suman 4.134 personas representando un 40.58% de los encuestados.</p>
<section id="recodificación-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="recodificación-de-variables">Recodificación de variables</h2>
<section id="variable-binaria-de-zona" class="level3">
<h3 class="anchored" data-anchor-id="variable-binaria-de-zona">Variable binaria de zona</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=10188 valid N=10188 mean=0.14 sd=0.35

Value |  Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------
    0 | Urbano | 8722 | 85.61 |   85.61 |  85.61
    1 |  Rural | 1466 | 14.39 |   14.39 | 100.00
 &lt;NA&gt; |   &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>De una muestra poblacional de 10188 encuestados, 8.722 corresponden a urbanos y 1.466 a rural.</p>
</section>
<section id="variable-nivel-educacional" class="level3">
<h3 class="anchored" data-anchor-id="variable-nivel-educacional">Variable nivel educacional</h3>
</section>
</section>
<section id="recodificación-nivel-educacional" class="level2">
<h2 class="anchored" data-anchor-id="recodificación-nivel-educacional">Recodificación nivel educacional</h2>
<p>Se recodifica la variable de nivel educacional para trabajar con menos categorías y facilitar el análisis. La recodificación queda de la siguiente manera: Se denomina como analfabeto a quienes están en el N°1= nunca asistió, N° 2 sala cuna, N° 3 jardín infantil (medio menor y medio mayor), N° 4 Prekinder/ Kínder. El segundo grupo &nbsp;es Enseñanza básica= N°6, primaria o preparatoria (sistema antiguo), N°7 educación básica. Enseñanza media = N°8, Humanidades (sistema antiguo), N°9 Educación media científico humanista, N°10 Técnica comercial, Industrial o Normalista (sistema antiguo) N° 11 Educación media Técnico profesional. Enseñanza superior= N° 12 Técnico Nivel Superior Incompleto (carrera de 1 a 3 años) N° 13 Técnico Nivel Superior Completo (carreras de 1 a 3 años) N°14, Profesional incompleto (Carreras de 4 o más años) N° 15, Profesional Completo (Carreras de 4 o más años) N° 16 Postgrado incompleto, N°17 Post grado completo. Además la educación especial queda en una categoría diferenciada porque no se especifica a que se refiere esta categoría, por lo que no se agrupa con los demás niveles.&nbsp;</p>
</section>
<section id="graficos" class="level2">
<h2 class="anchored" data-anchor-id="graficos">Graficos</h2>
<p>proc_data$nivel_educ &lt;- car::recode(proc_data$nivel_educ, “c(1,2,3,4)=1; c(5)=2; c(6,7)=3; c(8,9,10,11)=4;</p>
<p>c(12,13,14,15,16,17)=5”)</p>
<p>proc_data2 = proc_data</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Trabajo4_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Trabajo4_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Trabajo4_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Gráfico N° 1, eleboración propia, este gráfico de barras muestra el Nivel Educacional. Se puede apreciar que la moda es educación media, además las categorías con menos casos son las de analfabeto y educación especial.&nbsp;</p>
<p>&nbsp;Gráfico N° 2 , elaboración propia, este gráfico de barras satis-ingreso, a simple vista parece bimodal, se puede apreciar que la moda (4 satisfecho) es muy parecida a (2 insatisfecho), sin embargo, el promedio es 2.93,lo que indica que hay una baja satisfacción con los ingresos.</p>
<p>Gráfico N° 3, elaboración propia, este gráfico de barras, satisfacción con la vivienda, la moda es la N° 4 “satisfecho” , por lo que se puede decir que la mayoría de las personas encuestadas se siente satisfecha o totalmente satisfecha con su vivienda.</p>
<p>Con esta visión general de los datos podemos analizar la asociación entre las variables (trabajo 3 enviado)</p>
</section>
<section id="se-agregar-gráfico-y-el-análisis-del-trabajo-3" class="level2">
<h2 class="anchored" data-anchor-id="se-agregar-gráfico-y-el-análisis-del-trabajo-3">SE AGREGAR GRÁFICO Y EL ANÁLISIS DEL TRABAJO 3</h2>
<section id="este-trabajo-fue-enviado-aparte-anteriormente-pero-se-incluye-el-gráfico-de-matriz-con-el-correcto-análisis" class="level4">
<h4 class="anchored" data-anchor-id="este-trabajo-fue-enviado-aparte-anteriormente-pero-se-incluye-el-gráfico-de-matriz-con-el-correcto-análisis">Este trabajo fue enviado aparte, anteriormente, pero se incluye el gráfico de matriz con el correcto análisis</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Trabajo4_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Gráfico N° 4, eleboración propia. Este gráfico/matriz representa el grado de asociación entre variables mediante el tamaño de los círculos e intensidad de colores, y el signo de la asociación se representa con una gradiente de colores que va del azul (positivo) al rojo (negativo). Por lo tanto, se puede ver que la mayor asociación es entre nivel educacional e ingresos con 0.37 que corresponde a una relación moderada. También se observa que las correlaciones de las variables son positivas, excepto la asociación de las variables zona-nivel educacional, que da un valor negativo -0.18, lo que indica que es una asociación con fuerte correlación negativa y que corresponde el valor más bajo de este gráfico</p>
</section>
</section>
</section>
<section id="trabajo-4" class="level1">
<h1>TRABAJO 4</h1>
<section id="tabla-descriptiva" class="level2">
<h2 class="anchored" data-anchor-id="tabla-descriptiva">Tabla descriptiva</h2>
<p>Regresión</p>
<div class="cell">
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<caption>Data frame: proc_data</caption>
<tbody><tr>
<th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">ID</th><th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">Name</th><th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">Label</th><th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">Values</th><th style="border-bottom:double; font-style:italic; font-weight:normal; padding:0.2cm; text-align:left; vertical-align:top;">Value Labels</th>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">nivel_educ</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;"></td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1<br>2<br>3<br>4<br>5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">Analfabeto<br>Educación especial<br>Educación básica<br>Educación media<br>Educación superior</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">2</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">satisniveleducacional</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">satisfacción con el  nivel educacional</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">1<br>2<br>3<br>4<br>5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">1. Totalmente insatisfecho<br>2. Insatisfecho<br>3. Indiferente<br>4. Satisfecho<br>5. Totalmente satisfecho</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">3</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">satis_ingreso</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">satisfacción con los ingresos</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1<br>2<br>3<br>4<br>5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1. Totalmente insatisfecho<br>2. Insatisfecho<br>3. Indiferente<br>4. Satisfecho<br>5. Totalmente satisfecho</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">4</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">satis_vivienda</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">satisfacción con la vivienda</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">1<br>2<br>3<br>4<br>5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">1. Totalmente insatisfecho<br>2. Insatisfecho<br>3. Indiferente<br>4. Satisfecho<br>5. Totalmente satisfecho</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">educ_ingresos</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">efecto de la educación sobre los ingresos</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1<br>2<br>3<br>4<br>5</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top;">1. Nada<br>2. Poco<br>3. Algo<br>4. Bastante<br>5. Mucho</td>
</tr>
<tr>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">6</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">zona</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee"></td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">0<br>1</td>
<td style="padding:0.2cm; text-align:left; vertical-align:top; background-color:#eeeeee">Urbano<br>Rural</td>
</tr>

</tbody></table>
</div>
</div>
</section>
<section id="regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal">Regresión lineal</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;Statistical models&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 1&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 2&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Modelo 3&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(Intercept)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1.39&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;2.93&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;2.83&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.01)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.01)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;zona&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.19&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.06&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-0.18&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.03)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.04)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;10188&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;10188&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;10188&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="4"&gt;&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.001; &lt;sup&gt;&amp;#42;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.01; &lt;sup&gt;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>En el modelo 1 se incluye zona como predictor, que tiene como coeficiente de regresión -0,40. Esto indica que, disminuye la población de la zona rural en 0.40 unidades. Efecto que lo podemos extrapolar a la población con un 99,9 % de confianza (p&lt; 0,001) El intercepto de 4.20, lo que indica que (teóricamente) las personas de zona urbana tienen una educación de 4.20. El R2 indica el modelo 1 logra explicar el 3% de la varianza de la variable dependiente (R2=0,03)</p>
<p>En el modelo 2 se incluye zona como predictor, que tiene como coeficiente de regresión 0.06 Esto indica que, la satisfacción con el ingreso en zona rural es de 0.06 mayor que la satisfacción de las personas en zona urbana. no es estadísticamente significativo (p&lt;0,01) El intercepto de 2.93, lo que indica que (teóricamente) las personas de zona urbana tienen una satisfacción con el ingreso de 2.93. El R2 indica el modelo 2 logra explicar el 0% de la varianza de la variable dependiente (R2=0,00)</p>
<p>En el modelo 3 se incluye zona como predictor, que tiene como coeficiente de regresión -0.18 Esto indica que, el efecto de la educación sobre el ingreso disminuye en la población de la zona rural en -0.18 unidades. Efecto que lo podemos extrapolar a la población con un 99, 9% de confianza (p&lt; 0.001) El intercepto de 2.83, lo que indica que (teóricamente) las personas de zona urbana tienen efecto de la educación sobre el ingreso de 2.83. El R2 indica el modelo 3 logra explicar el 0% de la varianza de la variable dependiente (R2=0,00)</p>
</section>
<section id="graficar" class="level2">
<h2 class="anchored" data-anchor-id="graficar">Graficar</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="Trabajo4_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Grafico N° 5, elaboración propia, Para analizar este gráfico se hará mención también al modelo de regresión estimado, el gráfico muestra que hay una distribución desigual de la población entre las diferentes zonas. La zona urbana tiene un nivel educacional de la población significativamente mayor que la zona rural, según la muestra poblacional.</p>
</section>
<section id="notas-explicativas" class="level2">
<h2 class="anchored" data-anchor-id="notas-explicativas">Notas explicativas</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=10188 valid N=10188 mean=0.00 sd=0.00

Value |  Label |     N | Raw % | Valid % | Cum. %
-------------------------------------------------
    0 | Urbano | 10188 |   100 |     100 |    100
    1 |  Rural |     0 |     0 |       0 |    100
 &lt;NA&gt; |   &lt;NA&gt; |     0 |     0 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>Se recodificó la variable categórica “zona” (urbano 0 y rural 1) Esto para poder hacer la regresión lineal, facilitar la comprensión de los resultados y presentarlo en un formato compatible.</p>
<p>Tambien para la obtención del modelo se mantuvo la variable de nivel educaional como numérica</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>